# -*- coding: utf-8 -*-
"""Text_generator_RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXUZg7-1kTjYSMbp-Ps5mwPLRLbzFA0A
"""

import tensorflow as tf
import numpy as np
import pandas as pd
import random
import sys

df = pd.read_csv('/content/train (4).csv', on_bad_lines='skip', engine='python')
text = " ".join(df['text'].dropna().astype(str)).lower()

print(f'Total characters in text: {len(text)}')

vocab = sorted(set(text))
print(f'Vocabulary size: {len(vocab)}')

char2idx = {c: i for i, c in enumerate(vocab)}
idx2char = np.array(vocab)

text_as_int = np.array([char2idx[c] for c in text])

seq_length = 100

char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)

sequences = char_dataset.batch(seq_length + 1, drop_remainder=True)

def split_input_target(chunk):
    return chunk[:-1], chunk[1:]

dataset = sequences.map(split_input_target)

BATCH_SIZE = 64
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

vocab_size = len(vocab)
embedding_dim = 64
rnn_units = 128

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_shape=(None,)),
    tf.keras.layers.LSTM(rnn_units, return_sequences=True, recurrent_initializer='glorot_uniform'),
    tf.keras.layers.Dense(vocab_size)
])


def loss(labels, logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

model.compile(optimizer='adam', loss=loss)

model.summary()

EPOCHS = 20
history = model.fit(dataset, epochs=EPOCHS)

def generate_text(model, start_string, num_generate=100, temperature=1.0):
    input_eval = [char2idx.get(s, 0) for s in start_string.lower()]
    input_eval = tf.expand_dims(input_eval, 0)

    text_generated = []

    model.layers[1].reset_states()

    for _ in range(num_generate):
        predictions = model(input_eval)
        predictions = tf.squeeze(predictions, 0) / temperature
        predicted_id = tf.random.categorical(
            predictions, num_samples=1)[-1, 0].numpy()

        input_eval = tf.expand_dims([predicted_id], 0)
        text_generated.append(idx2char[predicted_id])

    return start_string + ''.join(text_generated)


print(generate_text(model, start_string="The ", num_generate=200, temperature=0.8))

"""## Text Generation Report

This notebook demonstrates a character-level text generation model using a Long Short-Term Memory (LSTM) neural network with TensorFlow and Keras.

### 1. Data Loading and Preprocessing

The text data was loaded from a CSV file named `train (4).csv`. Initially, there were `ParserError` issues due to malformed lines in the CSV. These were resolved by using `pd.read_csv` with `on_bad_lines='skip'` and `engine='python'` to gracefully handle and skip problematic rows. The 'text' column from the DataFrame was then extracted, concatenated into a single string, and converted to lowercase. The total number of characters processed was `15990357`.

A vocabulary of unique characters was created from this text, resulting in a `vocabulary size` of `92`. Each character was mapped to an integer (`char2idx`), and vice versa (`idx2char`), for numerical processing by the model.

### 2. Dataset Preparation

The integer-encoded text was then prepared into sequences for training. Each sequence has a length of `100` characters. These sequences were batched with a `BATCH_SIZE` of `64`, with each batch containing an input sequence and its corresponding target sequence (the input shifted by one character).

### 3. Model Architecture

The text generation model is a `tf.keras.Sequential` model consisting of three layers:

*   **Embedding Layer**: Maps each character integer to a dense vector of `embedding_dim = 64` dimensions.
*   **LSTM Layer**: A recurrent neural network layer with `rnn_units = 128` units, configured to return sequences. This layer learns long-term dependencies in the character sequences.
*   **Dense Layer**: An output layer with `vocab_size = 92` units, corresponding to the number of unique characters. This layer predicts the likelihood of each character being the next in the sequence.

The model was compiled using the `adam` optimizer and `sparse_categorical_crossentropy` as the loss function, suitable for predicting the next character from a set of possible characters.

### 4. Training

The model was trained for `20` `EPOCHS` on the prepared dataset. The training process iteratively updated the model's weights to minimize the prediction loss.

### 5. Text Generation

After training, the `generate_text` function was used to generate new text. This function takes the trained model, a starting string, the number of characters to generate (`num_generate`), and a `temperature` parameter (controlling the randomness of predictions) as input. The generated text for the starting string "The " with `num_generate=200` and `temperature=0.8` was:

```
The dg ing o  p’s havexp. go inecate at as touranox is alaron canched cansedern tomanan tid ed pritorwive teeud s gepal tidein, tsthe arthes cinderut shititerecthed is he ane mive fooongr wede in peang k
```
"""